AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AWSLambdaEmailService:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x 
      MemorySize: 512
      Timeout: 10
      CodeUri: ./
      Events:
        EmailEvent:
          Type: Api 
          Properties:
            Path: /
            Method: POST